### ISSUE TITLE
Many cyclonedx-dotnet issues are outdated

### ISSUE THREAD

**Issue by Bertk** [CycloneDX/cyclonedx-dotnet#700]
@coderpatros Could you please mark issues with labels and close outdated once.
I cleanup will be very helpful finding real bugs. Maybe you can allow authors to assign labels as well.

Maybe adding this workflow with „stale: 6 month period“ and „close: 12 month period“ will help.
https://docs.github.com/en/actions/managing-issues-and-pull-requests/closing-inactive-issues

**Comment by mtsfoni** [comment]
I left this untouched for a while because I felt indecisive about this issue.

I dislike the idea of auto closing unresolved issues and rather try to have a look at each of them.

What I instead would like to do: is having labels like "Information needed" that auto close after eg. 2 weeks, to avoid outdated issue that cannot be resolved or viewed as backlog.

**Comment by mtsfoni** [comment]
I merged your PR.

Also introduced a label `ready for development` to help potential contributors to find relevant issues.
