### ISSUE TITLE
dotnet CycloneDX Use these two parameters: --exclude-test-projects --exclude-dev why doesn't it work? I want to delete the name in the box

### ISSUE THREAD

**Issue by JY1990** [CycloneDX/cyclonedx-dotnet#841]
<img width="379" alt="企业微信截图_17061536594139" src="https://github.com/CycloneDX/cyclonedx-dotnet/assets/74392941/a604ec5d-c59d-4d50-9245-ebda49eef4b4">

**Comment by JY1990** [comment]
![Uploading 企业微信截图_17061536731614.png…]()

**Comment by JY1990** [comment]
<img width="386" alt="企业微信截图_17061536731614" src="https://github.com/CycloneDX/cyclonedx-dotnet/assets/74392941/8e400281-1736-4d16-a889-a2725ad9df1d">

**Comment by JY1990** [comment]
Execute the command：dotnet CycloneDX .\Nova.sln -o C:\Desktop\server\ --exclude-test-projects --exclude-dev -dgl Why did the name SLN appear   How do I fix this? The version used is 3.0.5

**Comment by mtsfoni** [comment]
This is the name of your application. It's the root for all dependencies. The component node is under the metadata node, and is not a "dependency-component". You cannot remove it, because that's what your dependencies hang on.

You can however change its name and version with the `-sn` and `-sv` argument or by importing a metafile `-imp`

**Comment by mtsfoni** [comment]
Closing as `-sn` should be your solution. If you still have a problem, feel free to write again.
